#################################################################
# Minimal beta stack: backend (fhir-server), frontend (fhir-admin), haproxy
# - No Couchbase in this compose (assumes backend can start without DB or uses in‑memory / external)
# - Only port 80 exposed publicly via HAProxy
# - Internal service names match those in haproxy.cfg (fhir-server, fhir-admin)
# - If backend requires config.yaml, it's mounted read-only
#################################################################

services:
  fhir-server:
    build:
      context: ./backend
    mem_limit: 3g
    mem_reservation: 2g
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DEPLOYED_ENV: container
      # Tomcat thread pool tuning (tune for your load)
      SERVER_TOMCAT_THREADS_MAX: 100 # Max threads (was 50, increase for higher concurrency)
      SERVER_TOMCAT_THREADS_MIN_SPARE: 20 # Minimum idle threads
      SERVER_TOMCAT_ACCEPT_COUNT: 200 # Queue size when all threads busy
      SERVER_TOMCAT_MAX_CONNECTIONS: 300 # Max simultaneous connections
      SERVER_TOMCAT_CONNECTION_TIMEOUT: 20s # Connection timeout
      SERVER_TOMCAT_MAX_KEEP_ALIVE_REQUESTS: 1000 # Keep-alive requests per connection
      JAVA_TOOL_OPTIONS: >-
        -Xms1g
        -Xmx2g
        -Xss512k
        -XX:MaxDirectMemorySize=512m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/app/logs/heap.hprof
        -XX:+ExitOnOutOfMemoryError
        -Xlog:gc*:file=/app/logs/gc.log:time,uptime,level,tags:filecount=5,filesize=10M
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    expose:
      - "8080" # internal only; not published to host
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./logs:/app/logs # Added volume mount to access JFR and other log files
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    restart: no # unless-stopped . Changed to no to prevent restart on container restart.
  fhir-admin:
    build:
      context: ./frontend
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    expose:
      - "80" # internal only; served through haproxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    depends_on:
      - fhir-server
    restart: unless-stopped

  # auth-server:
  #   build:
  #     context: ./auth
  #   environment:
  #     - BETTER_AUTH_URL=http://localhost
  #   volumes:
  #     - auth_db_data:/app/db
  #     - ./config.yaml:/app/config.yaml
  #   restart: unless-stopped

  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "80:80" # only public entry
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - fhir-admin
      - fhir-server
    restart: unless-stopped

  auth-server:
    build:
      context: ./auth
    environment:
      - BETTER_AUTH_URL=http://localhost
    volumes:
      - auth_db_data:/app/db
      - ./config.yaml:/app/config.yaml
    # expose:
    #   - 5000
    # ports:
    #   - "5000:5000"
    restart: unless-stopped

volumes:
  couchbase_data: {}
  # haproxy_socket: {}
  auth_db_data: {}
