version: "3.8"

#################################################################
# Minimal beta stack: backend (fhir-server), frontend (fhir-admin), haproxy
# - No Couchbase in this compose (assumes backend can start without DB or uses in‑memory / external)
# - Only port 80 exposed publicly via HAProxy
# - Internal service names match those in haproxy.cfg (fhir-server, fhir-admin)
# - If backend requires config.yaml, it's mounted read-only
#################################################################

services:
  fhir-server:
    build:
      context: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx1024m
      - DEPLOYED_ENV=container
    expose:
      - "8080" # internal only; not published to host
    volumes:
      - ./config.yaml:/config.yaml:ro
    restart: unless-stopped
  fhir-admin:
    build:
      context: ./frontend
    expose:
      - "80" # internal only; served through haproxy
    depends_on:
      - fhir-server
    restart: unless-stopped

  # auth-server:
  #   build:
  #     context: ./auth
  #   environment:
  #     - BETTER_AUTH_URL=http://localhost
  #   volumes:
  #     - auth_db_data:/app/db
  #     - ./config.yaml:/app/config.yaml
  #   restart: unless-stopped

  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "80:80" # only public entry
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - fhir-admin
      - fhir-server
    restart: unless-stopped

  auth-server:
    build:
      context: ./auth
    environment:
      - BETTER_AUTH_URL=http://localhost
    volumes:
      - auth_db_data:/app/db
      - ./config.yaml:/app/config.yaml
    # expose:
    #   - 5000
    # ports:
    #   - "5000:5000"
    restart: unless-stopped

volumes:
  couchbase_data: {}
  # haproxy_socket: {}
  auth_db_data: {}
